mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
    url(r'^close_window/$', 'mysite.views.close_window'),
    url(r'^accounts/(?P<username>[\w_-]+)/edit/$', 'dirplace.views.editProfile',name= 'userena_profile_edit'),
    url(r'^search-results/$', 'dirplace.views.search_results'),
    url(r'^categories/(?P<category_slug>[\w_-]+)/$', 'dirplace.views.search_by_category'),
    url(r'^categories/(?P<category_slug>[\w_-]+)/(?P<subCategory_slug>[\w_-]+)/$', 'dirplace.views.search_by_subCategory'),
    url(r'^categories/(?P<category_slug>[\w_-]+)/(?P<subCategory_slug>[\w_-]+)/(?P<tag_slug>[\w_-]+)/$', 'dirplace.views.search_by_tag'),
    url(r'^about-us/$', 'dirplace.views.about_us'),
    url(r'^faqs/$', 'dirplace.views.faqs'),
    url(r'^contact-us/$', 'dirplace.views.contact'),
    url(r'^contact_thanks/', 'dirplace.views.contact_thanks'),
    url(r'^terms-and-conditions/$', 'dirplace.views.terms_and_conditions'),
    url(r'^privacy-policy/$', 'dirplace.views.privacy_policy'),
    url(r'^get-add-for-android/$', 'dirplace.views.get_add_for_android'),
    (r'^accounts/', include('userena.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '/media'}),
    url(r'^captcha/', include('captcha.urls')),
)

dirplace/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.utils.encoding import smart_str, smart_unicode
from django.conf import settings
from django import forms as forms
from django.forms.widgets import *
from django.core.mail import send_mail, BadHeaderError
from djangoratings.fields import RatingField
from mptt.models import MPTTModel, TreeForeignKey
from userena.models import UserenaBaseProfile
from unidecode import unidecode
import datetime
import requests
import re
import string
import random
import os.path

def id_generator(size=9, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

def userPicture_file_name(instance, filename):
    if not filename:
        return ""
    exts = re.search('[.]([^.]*)$',filename)
    if exts is None:
        ext  = ''
    else:
        ext = '.'+exts.group(1)
    return '/'.join(['uploaded/users/', str(instance.id), '/'+id_generator(27)+'%s' % (ext)])

def promotionPicture_file_name(instance, filename):
    if not filename:
        return ""
    exts = re.search('[.]([^.]*)$',filename)
    if exts is None:
        ext  = ''
    else:
        ext = '.'+exts.group(1)
    return '/'.join(['uploaded/promotions/', str(instance.id), '/'+id_generator(27)+'%s' % (ext)])

class UserProfile(UserenaBaseProfile):
    MARITAL_STATUSES = (
        ('SIN', 'Single'),
        ('MAR', 'Married'),
        ('SEP', 'Separated'),
        ('DIV', 'Divorced'),
        ('WID', 'Widowed'),
        ('COH', 'Cohabiting'),
    )
    GENRES = (
        ('FEM', 'Female'),
        ('MAL', 'Male'),
    )
    PRIVACY_OPTIONS = (
        ('open', 'Open'),
        ('registerd', 'Registered'),
        ('closed', 'Closed'),
    )
    user = models.OneToOneField(User,unique=True,verbose_name=_('user'),related_name='my_profile')
    birth_date = models.DateTimeField(null=True, blank=True)
    genre = models.CharField(max_length=3, choices=GENRES, null=True, blank=True)
    occupation = models.ForeignKey('Occupation', null=True, blank=True)
    marital_status = models.CharField(max_length=3, choices=MARITAL_STATUSES, null=True, blank=True)
    qrcode = models.CharField(max_length=36, null = True, blank=True)
    added_date = models.DateTimeField(null=True, blank=True)
    last_update = models.DateTimeField(null=True, blank=True)
    picture = models.ImageField(upload_to=userPicture_file_name, null=True, blank=True)
    def __unicode__(self):
        return self.user.email
    def save(self, *args, **kwargs):
        if self.id is not None:
            self.last_update = datetime.datetime.now()
        else:
            self.added_date = datetime.datetime.now()
            self.last_update = datetime.datetime.now()
        super(UserProfile, self).save(*args, **kwargs)
    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"


class Occupation(models.Model):
    name = models.CharField(max_length=81)
    name_es = models.CharField(max_length=81)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = "Occupation"
        verbose_name_plural = "Occupations"
        ordering = ['name']

class Place(models.Model):
    name = models.CharField(max_length=243)
    category = models.ForeignKey('Category')
    description = models.TextField()
    address1 = models.CharField(max_length=243, null=True, blank=True)
    address2 = models.CharField(max_length=243, null=True, blank=True)
    zip = models.CharField(max_length=9, null=True, blank=True)
    city = models.CharField(max_length=81, null=True, blank=True)
    state = models.CharField(max_length=81, null=True, blank=True)
    country = models.ForeignKey('Country', null=True, blank=True)
    phone = models.CharField(max_length=81, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    website = models.CharField(max_length=243, null=True, blank=True)
    open_hours = models.CharField(max_length=255, null=True, blank=True)
    added_date = models.DateTimeField(null=True, blank=True)
    last_update = models.DateTimeField(null=True, blank=True)
    rating = RatingField(range=5)
    def __unicode__(self):
        return self.name
    def save(self, *args, **kwargs):
        if self.id is not None:
            self.last_update_date = datetime.datetime.now()
        else:
            self.added_date = datetime.datetime.now()
            self.last_update_date = datetime.datetime.now()
        super(Place, self).save(*args, **kwargs)
    class Meta:
        verbose_name = "Place"
        verbose_name_plural = "Places"

class Category(MPTTModel):
    name = models.CharField(max_length=81)
    name_es = models.CharField(max_length=81)
    slug = models.CharField(max_length=255)
    slug_es = models.CharField(max_length=255)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['name']
    class MPTTMeta:
        order_insertion_by = ['name']

class Country(models.Model):
    iso2 = models.CharField(max_length=2, null=True, blank=True)
    short_name = models.CharField(max_length=80)
    long_name = models.CharField(max_length=80)
    iso3 = models.CharField(max_length=3, null=True, blank=True)
    numcode = models.CharField(max_length=6, null=True, blank=True)
    un_member = models.CharField(max_length=12, null=True, blank=True)
    calling_code = models.CharField(max_length=8, null=True, blank=True)
    cctld = models.CharField(max_length=5, null=True, blank=True)
    short_name_es = models.CharField(max_length=80)
    long_name_es = models.CharField(max_length=80)
    def __unicode__(self):
        return self.short_name
    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"
        ordering = ['short_name']

class Resource(models.Model):
    RESOURCE_TYPES = (
        ('PIC', 'Picture'),
        ('VID', 'Video'),
        ('FIL', 'File'),
    )
    place = models.ForeignKey('Place')
    type = models.CharField(max_length=3, choices=RESOURCE_TYPES, null=True, blank=True)
    content = models.CharField(max_length=255, null=True, blank=True)
    def __unicode__(self):
        return self.id
    class Meta:
        verbose_name = "Resource"
        verbose_name_plural = "Resources"

class Promotion(models.Model):
    PROMOTION_TYPES = (
        ('DIS', 'Discount'),
        ('COU', 'Coupon'),
        ('OFF', 'Offer'),
    )
    USERS_AGES = (
        ('ALL', 'All fans'),
        ('3MO', 'People who have been fans since at least the last 3 months'),
        ('1YE', 'People who have been fans since at least the last 12 months'),
    )
    place = models.ForeignKey('Place')
    type = models.CharField(max_length=3, choices=PROMOTION_TYPES, null=True, blank=True)
    description = models.CharField(max_length=81)
    gift = models.CharField(max_length=243, null=True, blank=True)
    involved_products = models.TextField(null=True, blank=True)
    from_date = models.DateTimeField(null=True, blank=True)
    to_date = models.DateTimeField(null=True, blank=True)
    picture = models.ImageField(upload_to=promotionPicture_file_name, null=True, blank=True)
    users_age = models.CharField(max_length=3, choices=USERS_AGES, null=True, blank=True)
    restrictions = models.TextField()
    added_date = models.DateTimeField(null=True, blank=True)
    last_update = models.DateTimeField(null=True, blank=True)
    def save(self, *args, **kwargs):
        if self.id is not None:
            self.last_update_date = datetime.datetime.now()
        else:
            self.added_date = datetime.datetime.now()
            self.last_update_date = datetime.datetime.now()
        super(Promotion, self).save(*args, **kwargs)
    def __unicode__(self):
        return self.description
    class Meta:
        verbose_name = "Promotion"
        verbose_name_plural = "Promotions"

dirplace/forms.py
from django import forms
from django.conf import settings
from django.db.models import Q
from django.core.context_processors import request
from django.core.files.images import get_image_dimensions
from django.forms import extras
from dirplace.models import UserProfile, Occupation
from datetime import date
from captcha.fields import CaptchaField
from userena import views as userena_forms

class ContactForm(forms.Form):
    name =  forms.CharField(max_length=81)
    email = forms.EmailField()
    description = forms.CharField(widget=forms.Textarea)
    captcha = CaptchaField()

class EditProfileForm(userena_forms.EditProfileForm):
    birth_date = forms.DateTimeField (required=False, widget=extras.SelectDateWidget(years=range(date.today().year - 11,date.today().year - 106,-1)))
    privacy = forms.CharField(widget=forms.HiddenInput(), initial='registered')

dirplace/views.py
from django.core.context_processors import request
from django.core.files.images import get_image_dimensions
from django.shortcuts import render_to_response, redirect
from django.template.context import Context, RequestContext
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.contrib.sites.models import Site
from django.db.models import Max
from django.db import connection, transaction
from django.conf import settings
from dirplace.models import *
from dirplace.forms import *
from templated_email import send_templated_mail
from array import *
from cStringIO import StringIO
from tokenize import generate_tokens
from time import strftime, strptime
from random import randrange
from userena import views as userena_views
import datetime
import json
import requests
import urlparse
import urllib
import string
import random

def search_results(request):
    c = {}
    return render_to_response ('dirplace/search-results.html', c, context_instance =  RequestContext(request),)

def search_by_category(request, category_slug):
    theCategory = Category.objects.get(slug=category_slug);
    subCategories = Category.objects.filter(parent_id=theCategory.id)
    c = {
            'theCategory':theCategory,
            'subCategories':subCategories,
    }
    return render_to_response ('dirplace/search-by-category.html', c, context_instance =  RequestContext(request),)

def search_by_subCategory(request, category_slug, subCategory_slug):
    theCategory = Category.objects.get(slug=category_slug);
    theSubCategory = Category.objects.get(slug=subCategory_slug);
    tags = Category.objects.filter(parent_id=theSubCategory.id)
    c = {
            'theCategory':theCategory,
            'theSubCategory':theSubCategory,
            'tags':tags,
    }
    return render_to_response ('dirplace/search-by-subCategory.html', c, context_instance =  RequestContext(request),)

def search_by_tag(request, category_slug, subCategory_slug, tag_slug):
    theCategory = Category.objects.get(slug=category_slug);
    theSubCategory = Category.objects.get(slug=subCategory_slug);
    theTag = Category.objects.get(slug=tag_slug);
    c = {
            'theCategory':theCategory,
            'theSubCategory':theSubCategory,
            'theTag':theTag,
    }
    return render_to_response ('dirplace/search-by-tag.html', c, context_instance =  RequestContext(request),)

def about_us(request):
    c = {}
    return render_to_response ('dirplace/about-us.html', c, context_instance =  RequestContext(request),)

def faqs(request):
    c = {}
    return render_to_response ('dirplace/faqs.html', c, context_instance =  RequestContext(request),)

def terms_and_conditions(request):
    c = {}
    return render_to_response ('dirplace/terms-and-conditions.html', c, context_instance =  RequestContext(request),)

def privacy_policy(request):
    c = {}
    return render_to_response ('dirplace/privacy-policy.html', c, context_instance =  RequestContext(request),)

def get_add_for_android(request):
    c = {}
    return render_to_response ('dirplace/get-add-for-android.html', c, context_instance =  RequestContext(request),)

def contact(request):
    EMAIL_CUSTOMER_ATTENDANT  = getattr(settings, 'EMAIL_CUSTOMER_ATTENDANT', 'omar@dirplace.com')
    DEFAULT_FROM_EMAIL = getattr(settings, 'DEFAULT_FROM_EMAIL', 'info@dirplace.com')
    DOMAINURL = getattr(settings, 'DOMAINURL', 'http://dirplace.com/')
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = 'Please reply to: ' + cd['email'] + '\n\n\n'
            message = message + cd['description']
            send_templated_mail(
                    template_name='contact-notification',
                    from_email=DEFAULT_FROM_EMAIL,
                    recipient_list=[EMAIL_CUSTOMER_ATTENDANT],
                    context={
                        'message':message,
                    },
            )
            return redirect('/dirplace/contact_thanks/')
    else:
        form = ContactForm()
    c = {
            'form': form
    }
    return render_to_response ('dirplace/contact-us.html', c, context_instance =  RequestContext(request),)

def contact_thanks(request):
    c = {}
    return render_to_response ('dirplace/contact_thanks.html', c, context_instance =  RequestContext(request),)

def editProfile(request, username):
    theUser = User.objects.get(username=username);
    theUserProfile = UserProfile.objects.get(user_id=theUser.id);
    successMessage = False
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            theUser.first_name = cd["first_name"]
            theUser.last_name = cd["last_name"]
            theUser.save()
            if request.POST.get('mugshot-clear', False):
                theUserProfile.mugshot = None
            else:
                if cd["mugshot"]:
                    theUserProfile.mugshot = cd["mugshot"]
            theUserProfile.birth_date = cd["birth_date"]
            theUserProfile.genre = cd["genre"]
            theUserProfile.occupation = cd["occupation"]
            theUserProfile.marital_status = cd["marital_status"]
            theUserProfile.save()
            successMessage = True
            form = EditProfileForm(initial={
                                        'first_name':theUser.first_name,
                                        'last_name':theUser.last_name,
                                        'mugshot':theUserProfile.mugshot,
                                        'birth_date':theUserProfile.birth_date,
                                        'genre':theUserProfile.genre,
                                        'occupation': theUserProfile.occupation,
                                        'marital_status': theUserProfile.marital_status,
                                    }
                            )
    else:
        form = EditProfileForm(initial={
                                        'first_name':theUser.first_name,
                                        'last_name':theUser.last_name,
                                        'mugshot':theUserProfile.mugshot,
                                        'birth_date':theUserProfile.birth_date,
                                        'genre':theUserProfile.genre,
                                        'occupation': theUserProfile.occupation,
                                        'marital_status': theUserProfile.marital_status,
                                    }
                            )

    c = {
            'username':username,
            'theUser':theUser,
            'theUserProfile':theUserProfile,
            'form': form,
            'successMessage': successMessage,
        }
    return render_to_response ('dirplace/edit_profile.html', c, context_instance =  RequestContext(request),)

templates/dirplace/about-us.html
{% extends "base.html" %}

{% block metaproperties %}
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="About dirPlace" />
	<meta property="og:description" content="dirPlace is a social utility that allows businesses to build an online community of loyal customers and allows users to find out local discounts, coupons and offers."/>
	<meta property="og:url" content="http://dirplace.com/"/>
	<meta property="og:image" content="http://dirplace.com/images/logo-mobile.gif"/>
	<meta property="og:type" content="website"/>
	<meta property="og:site_name" content="dirPlace"/>
{% endblock metaproperties %}

{% block seoSnippet %}
    <title>About dirPlace</title>
    <meta name="description" content="dirPlace is a social utility that allows businesses to build an online community of loyal customers and allows users to find out local discounts, coupons and offers.">
{% endblock seoSnippet %}

{% block maincontent %}
<br clear="all"/>
<h1>About dirPlace</h1>
<br clear="all"/>
<h2><i>Your business gets money, your customers save money.</i></h2>
<br clear="all"/>
<p>
    <i>This page was written on 2014.</i>
</p>
<br clear="all"/>
<p>
    Between 2014 and 2015, Internet is finishing a stage and starting a new one. Not everyone, but some people are aware of it,
    especially if they are using Internet from mid-1990s. Since that time, Internet has affected the world in different ways: Socially,
    politically and economically. Now, Internet is not centered exclusively around the web anymore, but it's an omnipresent resource in our lives. At this time,
    we are using Internet more socially and locally than ever and we can use it anywhere through desktop computers, mobile devices, cars and a big
    list of online electronic devices that send many real-time queries and transactions along the day, every day. And dirPlace
    is here to serve as a free and useful resource to connect people and businesses in this <b>new age of Internet</b>, and with real benefit for both parties.
</p>
<br clear="all"/>
<p>
    Before the launch, we planned to build a resource to help people to find out places where they can save money while they consume products or
    services. And, at the same time, this resource could be a great marketing tool for business owners; a tool with a great
    ROI because the platform can be used <b>for free</b> at the initial setup; if someone registers a business, the only initial "payment" we ask for in return for the use of this platform
    is a <b>promotion</b> for our individual users: A discount, a coupon or an offer. Of course, dirPlace is a business
    itself, but customers only will pay when their businesses reaches more than 1,000 fans. So, any business can use our platform
    for free initially. And this is true for any place, it doesn't matter if that is a huge well-known company or a tiny place.
</p>
<br clear="all"/>
<p>
    dirPlace works in a very easy way. Let's see an example. If you have a place (a
    restaurant, a stationery, a travel agency, etc) you can create an account, register your business and create a
    promotion for your fans. People in your city who use our internal search engine can find your business promotion (a
    discount, a coupon or an offer) and their interest can be catched: They become fans of your place, just like in
    others social networks but, in this case, there is a real benefit for both your business and your fans: You get a
    customer who wants to buy your product/service and, at the same time, this customer will save money. Great! At the
    end, you will be able to build a community of fans that become customers. And people can find great places with great
    promotions. <b>Your business gets money, your customers save money.</b>
</p>
<br clear="all"/>
<p>
    We hope you find our platform useful. It's our main interest. If  dirPlace is useful for enough people, then we will be successful.
</p>
<br clear="all"/>
<p>
    --
    <br/>
    Sincerely,
    <br/><br/>
    Omar Yesid Mari&ntilde;o<br/>
    Founder
    <br/><br/>
    - Skype ID: <i>omaryesid2007</i>
    <br/>
    - Twitter: <a href="http://www.twitter.com/OmarYesidMarino" target="_blank">@OmarYesidMarino</a>
    <br/>
    - E-mail: <a href="mailto:omar@dirplace.com">omar@dirplace.com</a>


</p>
{% endblock maincontent %}

templates/dirplace/contact-us.html
{% extends "base.html" %}

{% block mainhead %}
    {{ block.super }}
    <STYLE>
        #id_description {
            width: 100%;
            height:243px;
        }
    </STYLE>
{% endblock mainhead %}

{% block metaproperties %}
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="Contact us | dirPlace" />
	<meta property="og:description" content="Questions abour dirPlace - Contact us. We will reply shortly by e-mail."/>
	<meta property="og:url" content="http://dirplace.com/"/>
	<meta property="og:image" content="http://dirplace.com/images/logo-mobile.gif"/>
	<meta property="og:type" content="website"/>
	<meta property="og:site_name" content="dirPlace"/>
{% endblock metaproperties %}

{% block seoSnippet %}
    <title>Contact us | dirPlace</title>
    <meta name="description" content="Questions abour dirPlace - Contact us. We will reply shortly by e-mail.">
    <meta name="robots" content="noindex, follow">
{% endblock seoSnippet %}

{% block maincontent %}
<br clear="all"/>
<h1>Contact Us</h1>
<br clear="all"/>
<h3>Questions? Need a hand? We're here to help. However, initially you can take a look at our
<a href='{% url "home" %}faqs/'>FAQs (Frequently Asked Questions)</a>. Maybe we are answering your inquiry there. Otherwise, please complete
the following form and we will contact you soon:</h3>
<br clear="all"/>
<div class="contactForm">
    {% if form.errors %}
        <span class="redText">Please, correct the error{{ form.errors|pluralize }} described below:</span>
        <br clear="all"/><br/>
    {% endif %}
    <div>
        <form action="" method="post">
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.name.errors }}
                <div>
                    <b>Your name: </b>
                </div>
                <div>
                    {{ form.name }}
                </div>
            </div>
            <div class='simplePadding {% if form.email.errors %}errors{% endif %}'>
                {{ form.email.errors }}
                <div>
                    <b>Your e-mail: </b>
                </div>
                <div>
                    {{ form.email }}
                </div>
            </div>
            <div class='simplePadding {% if form.description.errors %}errors{% endif %}'>
                {{ form.description.errors }}
                <div>
                    <b>Tell us about it: </b>
                </div>
                <div>
                    {{ form.description }}
                </div>
            </div>
            <div class='simplePadding {% if form.description.errors %}errors{% endif %}'>
                {{ form.captcha.errors }}
                <div>
                    <b>You are a human being, right? If so, please write the letters or numbers you see in the image before clicking on submit button: </b>
                </div>
                <div>
                    {{ form.captcha }}
                </div>
            </div>
            <div class='simplePadding'>
                <input type="submit" value="Submit">
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock maincontent %}

templates/dirplace/contact_thanks.html
{% extends "base.html" %}

{% block metaproperties %}
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="Contact us | dirPlace" />
	<meta property="og:description" content="Questions abour dirPlace - Contact us. We will reply shortly by e-mail."/>
	<meta property="og:url" content="http://dirplace.com/"/>
	<meta property="og:image" content="http://dirplace.com/images/logo-mobile.gif"/>
	<meta property="og:type" content="website"/>
	<meta property="og:site_name" content="dirPlace"/>
{% endblock metaproperties %}

{% block seoSnippet %}
    <title>Contact us | dirPlace</title>
    <meta name="description" content="Questions abour dirPlace - Contact us. We will reply shortly by e-mail.">
    <meta name="robots" content="noindex, follow">
{% endblock seoSnippet %}

{% block maincontent %}
<br clear="all"/>
<h1>Contact Us</h1>
<br clear="all"/>
<div align="center">
    <h2>Thanks for your message. We're on it and will be in touch shortly.</h1>
    <br clear="all"/>
    <h3><a href="{% url "home" %}">Back to homepage</a></h2>
</div>
{% endblock maincontent %}

templates/dirplace/edit_profile.html
{% extends "base.html" %}

{% block mainhead %}
    {{ block.super }}
{% endblock mainhead %}

{% block metaproperties %}
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="Edit your profile | dirPlace" />
	<meta property="og:description" content="Edit your profile on dirPlace"/>
	<meta property="og:url" content="http://dirplace.com/"/>
	<meta property="og:image" content="http://dirplace.com/images/logo-mobile.gif"/>
	<meta property="og:type" content="website"/>
	<meta property="og:site_name" content="dirPlace"/>
{% endblock metaproperties %}

{% block seoSnippet %}
    <title>Edit your profile | dirPlace</title>
    <meta name="description" content="Edit your profile on dirPlace">
    <meta name="robots" content="noindex, follow">
{% endblock seoSnippet %}

{% block maincontent %}
<br clear="all"/>
<div id="profileNavigation">
    <ul id="box-nav">
        <a href="{% url "home" %}accounts/{{ username }}/">View profile</a>&nbsp;|&nbsp;
        <a href="{% url "home" %}accounts/{{ username }}/edit/">Edit details</a>&nbsp;|&nbsp;
        <a href="{% url "home" %}accounts/{{ username }}/password/">Change password</a>&nbsp;|&nbsp;
        <a href="{% url "home" %}accounts/{{ username }}/email/">Change email</a>
    </ul>
</div>
<br clear="all"/>
<h1>Edit your profile ({{ theUser.email }})</h1>
<br clear="all"/>
<h3>We encourage you to keep your profile up to date.</h3>
<br clear="all"/>
<div class="editProfileForm">
    {% if form.errors %}
        <span class="redText">Please, correct the error{{ form.errors|pluralize }} described below:</span>
        <br clear="all"/><br/>
    {% endif %}
    {% if successMessage %}
        <span class="greenText">Profile updated successfully - <a href="{% url "home" %}accounts/{{ username }}">View my new profile</a></span>
        <br clear="all"/><br/>
    {% endif %}
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.first_name.errors }}
                <div>
                    First name:
                </div>
                <div>
                    {{ form.first_name }}
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.last_name.errors }}
                <div>
                    Last name:
                </div>
                <div>
                    {{ form.last_name }}
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.mugshot.errors }}
                <div>
                    Your picture:
                </div>
                <div>
                    <span style="font-size:11px;">
                        {{ form.mugshot }}
                    </span>
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.birth_date.errors }}
                <div>
                    Birthdate:
                </div>
                <div>
                    {{ form.birth_date }}
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.genre.errors }}
                <div>
                    Gender:
                </div>
                <div>
                    {{ form.genre }}
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.occupation.errors }}
                <div>
                    Occupation:
                </div>
                <div>
                    {{ form.occupation }}
                </div>
            </div>
            <div class='simplePadding {% if form.name.errors %}errors{% endif %}'>
                {{ form.marital_status.errors }}
                <div>
                    Marital status:
                </div>
                <div>
                    {{ form.marital_status }}
                </div>
            </div>
            <div class='simplePadding'>
                {{ form.privacy }}
                <input type="submit" value="Submit">
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>
{% endblock maincontent %}